CREATE TABLE people (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT
);

CREATE TABLE horses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE people_and_horses (
    person_id INTEGER REFERENCES people (id),
    horse_id INTEGER REFERENCES horses (id),
    PRIMARY KEY (person_id, horse_id)
);
